# Copyright 2004-2010 OpenERP SA


{
    'name': 'I-Soft Subscription Management - Recurring',
    'version': '15.0.0.0.0',
    'category': 'Subscription Management',
    'license': 'AGPL-3',
    'author': "I-Soft Solutions",
    'website': 'https://github.com/oca/contract',
    'depends': ['base', 'account', 'analytic', 'sale', 'sale_subscription', 'industry_fsm', 'industry_fsm_sale','portal', 'project',
                'helpdesk', 'account_followup', 'crm', 'approvals'],
    'data': [

        'views/sale_subscription_view.xml',
        'views/sale_subscription_line.xml',
        'views/sale_view.xml',
        'views/subscription_machine_charge_view.xml',
        'views/subscription_portal_templates.xml',
        'views/subscription_rental_group_view.xml',
        'views/subscription_rental_factor_view.xml',
        'views/product_view.xml',
        'views/project_view.xml',
        'views/stock_production_lot_views.xml',
        'views/meter_reading_import_view.xml',
        'views/meter_reading_error_view.xml',
        'views/meter_click_combined_view.xml',
        'views/res_partner_view.xml',
        'views/crm_lead_views.xml',
        'views/account_move_views.xml',
        'views/purchase_views.xml',
        'views/approval_request_views.xml',
        'views/area_codes_views.xml',
        'views/account_bank_statement_views.xml',
        'views/account_report.xml',
        'views/report_invoice.xml',
        #'views/project_task_template_views.xml',
        'data/data.xml',
        'wizard/add_hoc_increase_views.xml',
        'wizard/meter_reading_request_views.xml',
        'wizard/sale_add_phantom_bom_view.xml',
        #'wizard/generate_recurring_invoices.xml',
        'wizard/sale_subscription_close_reason_wizard_views.xml',
        'security/ir.model.access.csv',
        'security/subscription_security.xml',
        'report/sale_report_templates.xml',
        'report/report_payment_remittance_templates.xml',
        'report.xml',

    ],
    'installable': True,
}
